version: '3.8'

services:
  ratio1-drive:
    build: .
    image: ratio1-drive:latest
    container_name: ratio1-drive
    ports:
      - "43935:43935"
    environment:
      - NODE_ENV=production
      - CSTORE_API_URL=http://host.docker.internal:8001
      - R1FS_API_URL=http://host.docker.internal:8002
    networks:
      - ratio1-network
    restart: unless-stopped

networks:
  ratio1-network:
    driver: bridge 